name: Tests
on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - master

  pull_request:
    paths-ignore:
      - 'docs/**'
    branches:
      - "**" 

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8] 
        poetry-version: [1.1.4]

    defaults:
          run:
            working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry ${{ matrix.poetry-version }}
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry==${{ matrix.poetry-version }}
          poetry --version
      - name: Install dependencies
        run: |
          python -m poetry install
      - name: Install GDAL
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin python3-gdal
      - name: Setup .env
        run: |
          cp .env.sample .env
      - name: Run unittest
        run: |
          python -m poetry run python manage.py test -v 2
      
